# Minimal GitLab CI/CD Configuration
stages:
  - publish

# Publish stage
publish:
  stage: publish
  script:
    - echo "Publish stage would run here"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always